bugtracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bugs/', include('bugtracker_app.urls')),
    path('', include('bugtracker_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

bugtracker_app/urls.py
from django.urls import path, include

from .views import Index
from .views import UpdateStatus
from .views import IssueDetail
from .views import RegisterView
from .views import NoteAPI
from .views import ProfileView
from .views import SolvedIssuesView
from .views import InProgressIssuesView
from .views import ThanksForReporteView
from .views import ErrorAfterReportView

app_name ='bugtracker'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('update/', UpdateStatus.as_view(), name='update_status'),
    path('api/note', NoteAPI.as_view(), name='note_api'),
    path('issue/<int:pk>', IssueDetail.as_view(), name='issue_detail'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/<int:pk>', ProfileView.as_view(), name='profile'),
    path('solved_issues/', SolvedIssuesView.as_view(), name='solved_issues'),
    path('in_progress_issues/', InProgressIssuesView.as_view(), name='in_progress_issues'),
    path('thanks/', ThanksForReporteView.as_view(), name='thanks_for_report'),
    path('error_after_report/', ErrorAfterReportView.as_view(), name='error_after_report'),
]

bugtracker_app/models.py
import uuid
from textwrap import shorten

from django.db import models
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from django.utils.deconstruct import deconstructible
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models.signals import pre_save
from django.dispatch import receiver


from . import models_default_values as mdv


class SingletonModel(models.Model):
    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        self.pk = 1
        super(SingletonModel, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        pass

    @classmethod
    def load(cls):
        obj, created = cls.objects.get_or_create(pk=1)
        return obj

class IssueCategory(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name        

class IssueArea(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

@deconstructible()
class IssueStatus(models.Model):
    name = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return self.name

    @classmethod
    def get_default(cls):
        return cls.objects.get_or_create(pk=1, name=mdv.status_name)

class IssueImportance(models.Model):
    priority = models.PositiveSmallIntegerField(unique=True)
    name = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return '%d - %s' % (self.priority, self.name)

class IssueVersion(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=False)
    status = models.CharField(max_length=255)
    date = models.DateField(
        null=True, blank=False,
        help_text='Дата выхода версии'
    )

class Issue(models.Model):
    subject = models.CharField(max_length=50)
    description = models.TextField()
    notify_by_email = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now_add=True)

    # for anonymous users
    author_name = models.CharField(max_length=30, null=True, blank=True)
    author_email = models.EmailField(null=True, blank=True)

    # FK
    author = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        null=True)

    status = models.ForeignKey(
        IssueStatus,
        on_delete=models.PROTECT,
        default=IssueStatus.get_default()[0])

    importance = models.ForeignKey(
        IssueImportance,
        on_delete=models.PROTECT)
    
    area = models.ForeignKey(
        IssueArea,
        on_delete=models.PROTECT)

    category = models.ForeignKey(
        IssueCategory,
        on_delete=models.PROTECT,
        default=0)

    version = models.ForeignKey(
        IssueVersion,
        on_delete=models.PROTECT,
        null=True, blank=True)

    def __str__(self):
        return 'Subject: %s Descr: %s' % (self.subject,
                                shorten(self.description, width=128, placeholder='...'))

    def get_absolute_url(self):
        return reverse('bugtracker:issue_detail', args=(self.id,))

    def set_author(self, user):
        self.author_name = user.first_name
        self.author_email = user.email
        self.author = user

class IssueComment(models.Model):
    content = models.TextField()
    from_username = models.CharField(max_length=255, null=True, blank=True)
    is_staff = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    # FK
    user = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name="comments",
        null=True, blank=True 
    )
    issue = models.ForeignKey(
        Issue,
        on_delete=models.PROTECT,
        related_name="comments"
    )

    reply_to = models.ForeignKey(
        'self',
        on_delete=models.PROTECT,
        null=True, blank=True,
        default=None,
        related_name='replies')

    def __str__(self):
        return 'From: %s Content: %s' % (self.from_username, self.content)

class Setting(SingletonModel):
    #REDMINE SETTINGS 
    redmine_url = models.CharField(max_length=255, default=mdv.redmine_url)
    redmine_api_access_key = models.CharField(max_length=100)
    project_id = models.CharField(max_length=255)
    redmine_sync_every_mins = models.PositiveSmallIntegerField(
        default=720,
        help_text='Как часто будет происходить синхронизация с redmine'
    )

    # TEMPLATES
    note_from_issue_author = models.TextField(
        default=mdv.note_from_issue_author,
        help_text='Заголовок комментария который отобразится в redmine'
    )
    comment_mail_template = models.TextField(
        default=mdv.comment_mail_template,
        help_text='Этот шаблон отправится клиенту на email, когда ему будет оставлен комментарий.'
    )
    error_after_report_template = models.TextField(
        default=mdv.error_after_report_template,
        help_text='''Этот шаблон отправится админу на email, 
        если на сайте произойдёт ошибка отправки заявки.'''
    )

    #EMAIL SETTINGS 
    smtp_email_client_host = models.CharField(default=mdv.smtp_host, max_length=200)
    smtp_email_client_port = models.PositiveIntegerField(default=mdv.smtp_port)
    imap_email_client_host = models.CharField(default=mdv.imap_host, max_length=200)
    imap_email_client_port = models.PositiveIntegerField(default=mdv.imap_port)
    email_login = models.CharField(max_length=255)
    email_password = models.CharField(max_length=255)

    #SELF SETTING
    api_key = models.UUIDField(default=uuid.uuid4, blank=False)
    company_name = models.CharField(default='', max_length=50)

    def __str__(self):
        return 'Setting'

# FORMS

class IssueForm(ModelForm):
    class Meta:
        model = Issue
        fields = ['subject', 'description', 'author_name', 'category',
         'author_email', 'notify_by_email', 'importance', 'area']

class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email', 'password1', 'password2', )

bugtracker_app/views.py
import json

import requests
from django.shortcuts import render, redirect

from django.contrib.auth import login
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin

from django.views.generic import TemplateView
from django.views.generic import ListView
from django.views.generic import DetailView
from django.views.generic import View

from django.http import HttpResponseBadRequest
from django.http import HttpResponseForbidden
from django.http import HttpResponse

from bugtracker_app.models import IssueForm
from bugtracker_app.models import RegisterForm
from bugtracker_app.models import Setting
from bugtracker_app.models import Issue
from bugtracker_app.models import IssueComment

from . import email_utils
from . import redmine
from . import utils
from .mymixins import CSRFExemptMixin


APP_NAME = 'bugtracker_app'

# Загружаем настройки
setting = Setting.load()

class Index(TemplateView):
    template_name = APP_NAME+'/index.html'

    def post(self, request):
        form = IssueForm(request.POST)
        if not form.is_valid():
            return self.get(request)

        issue = form.save(commit=False)
        if request.user.is_authenticated:
            issue.set_author(request.user)

        try:
            r = redmine.create_issue(issue)
            issue.id = r['issue']['id']
            issue.save()
        except Exception as e:
            email_utils.send_error_after_report_notify(request.user, e)
            return redirect('bugtracker:error_after_report')
        else:  
            request.session['report_issue_id'] = issue.id
            return redirect('bugtracker:thanks_for_report')
            

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['form'] = IssueForm()
        ctx['page_report'] = 'active' #for bs 3 navbar
        # FIXIT HARDCODING status__name
        ctx['in_progress'] = Issue.objects.filter(status__name='в работе')
        ctx['solved'] = Issue.objects.filter(status__name='решена')
        return ctx

class ThanksForReporteView(TemplateView):
    template_name = APP_NAME + '/alerts/thanks_for_report.html'

    def get(self, request):
        page = super().get(request)
        if request.session.get('report_issue_id'):
            self.request.session.pop('report_issue_id')
            return page
        else:
            return redirect('bugtracker:index')

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['report_issue_id'] = self.request.session.get('report_issue_id', None)
        return ctx

class ErrorAfterReportView(TemplateView):
    template_name = APP_NAME + '/alerts/error_after_report.html'

class UpdateStatus(TemplateView):
    template_name = APP_NAME+'/update_status.html'

    def post(self, request):
        utils.update_issues()
        return self.get(request)

class IssueDetail(DetailView):
    model = Issue
    # Add new comment
    def post(self, request, pk):
        reply = request.POST.get('reply', None)
        if reply:
            request.session['reply'] = reply
            return self.get(request, pk)
            
        comment_content = request.POST.get('comment')
        header = setting.note_from_issue_author
        response = redmine.create_note(pk, header+comment_content)
        if response.status_code == 200:
            comment = IssueComment.objects.create(
                content=comment_content,
                from_username=request.user.username,
                issue=self.get_object(),
                user=request.user  
            )
            if comment.issue.author != request.user:
                email_utils.send_comment_notify(comment)
        return self.get(request, pk)

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['reply'] = int(self.request.session.get('reply', -1))
        self.request.session['reply'] = -1
        return ctx

class ProfileView(LoginRequiredMixin, DetailView):
    model = User
    template_name = APP_NAME+'/profile.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['page_profile'] = 'active' #css class for BS 3 navbar
        ctx['comments'] = IssueComment.objects.filter(
            issue__author=self.get_object()).exclude(
            user=self.get_object())
        ctx['my_comments'] = IssueComment.objects.filter(
            user=self.get_object())
        # FIXIT HARDCODING status__name
        ctx['new'] = Issue.objects.filter(
            status__name='новая',
            author=self.get_object())
        ctx['in_progress'] = Issue.objects.filter(
            status__name='в работе')
        ctx['solved'] = Issue.objects.filter(
            status__name='решена',
            author=self.get_object())
        ctx['refused'] = Issue.objects.filter(
            status__name='отклонена',
            author=self.get_object())
        return ctx

class NoteAPI(CSRFExemptMixin, View):
    def post(self, request):
        api_key = str(setting.api_key).replace('-','')
        http_auth = request.META['HTTP_AUTHORIZATION']

        if http_auth != api_key:     
            return HttpResponseForbidden('api_key is not valid')

        data = json.loads(request.body.decode('utf-8'))
        try:
            comment = IssueComment.objects.create(is_staff=True, **data)
            email_utils.send_comment_notify(comment)
        except Exception as e:
            return HttpResponseBadRequest(
                content='Error when processing creation comment '+str(e)
            )
        return HttpResponse('OK')

class RegisterView(TemplateView):
    template_name = 'registration/register.html'
    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('bugtracker:index')
        else:
            return self.get(request)

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['form'] = RegisterForm()
        return ctx

class SolvedIssuesView(ListView):
    paginate_by = 10
    template_name = APP_NAME+'/solved_issues.html'

    def get_queryset(self):
        return Issue.objects.filter(status__name='решена')

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['page_solved'] = 'active' # for css class BS 3
        return ctx

class InProgressIssuesView(ListView):
    paginate_by = 10
    template_name = APP_NAME+'/in_progress_issues.html'

    def get_queryset(self):
        return Issue.objects.filter(status__name='в работе')

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['page_in_progress'] = 'active' # for css class BS 3
        return ctx

templates/bugtracker_app/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %} Заявить об ошибке {% endblock %}</title>
    <!-- JQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- Bootrstrap 3.3.7 JS -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- Bootrstrap 3.3.7 CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    {% block css %}

    {% endblock %}
    {% block js %}

    {% endblock %}
</head>
<body>
<header>
    {% include 'bugtracker_app/navbar.html' %} 
</header>

<main>
{% block content %}

{% endblock %}    
</main>
<footer>
    
</footer>
</body>
</html>

templates/bugtracker_app/form_errors.html
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger">
        <strong>{{ error|escape }}</strong>
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      <strong>{{ error|escape }}</strong>
    </div>
  {% endfor %}
{% endif %}

templates/bugtracker_app/in_progress_issues.html
{% extends 'bugtracker_app/issue_list.html'%}
{% block panel_class %}warning{%endblock%}
{% block list_title %}Заявки над которыми мы работаем{% endblock %}

templates/bugtracker_app/index.html
{% extends "bugtracker_app/base.html" %}

{% block title %} Заявить об ошибке {% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-md-6">
      {% include 'bugtracker_app/index/form_report_bug.html'%}
    </div>
  </div>
  
  <hr>
  <div class="row">
    <div class="col-sm-12"> 

      {% include 'bugtracker_app/index/in_progress_issues.html'%}
    </div>
  </div>

  <hr>
  <div class="row">    
    <div class="col-sm-12">
      {% include 'bugtracker_app/index/solved_issues.html'%}
    </div>    
  </div>

</div>
{% endblock %}



templates/bugtracker_app/issue_detail.html
{% extends 'bugtracker_app/base.html'%}

{% block title%}
  #{{issue.id}} {{issue.subject}}
{% endblock%}

{% block js %}
<script src="https://raw.githubusercontent.com/stewartlord/identicon.js/master/identicon.js"></script>
{% endblock %}

{% block content %}
  <div class="container">
  <!-- ISSUE DETAIL -->
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        {% include 'bugtracker_app/issue_detail/issue.html'%}
      </div>
    </div>

  <!-- ISSUE COMMENTS -->
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        {% include 'bugtracker_app/issue_detail/comments.html'%}
      </div>
    </div>
  </div>
{% endblock %}

templates/bugtracker_app/issue_list.html
{%extends 'bugtracker_app/base.html'%}

{% block content%}
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="panel panel-{% block panel_class %}default{%endblock%}">
        <div class="panel-heading">
          <h4>{% block list_title %} {% endblock %}</h4>
        </div>
        <div class="body">
          <table class="table table-striped table-hover">
            <thead style="font-weight: bold">
              <tr>
                <td>#</td>
                <td>Тема</td>
                <td>Описание</td>
              </tr>
            </thead>
            <tbody>
              {%for issue in object_list%}
              <tr onclick="window.location='{{issue.get_absolute_url}}';">
                <td>{{issue.id}}</td>
                <td>{{issue.subject}}</td>
                <td>{{issue.description|truncatewords:50}}</td>
              </tr>
              {% empty %}
              <tr>
                <td colspan="3"> Тут ничего нет </td>
              </tr>
              {%endfor%}  
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock%}

templates/bugtracker_app/navbar.html
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{%url 'bugtracker:index'%}">Россельхознадзор</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="{{page_report}}">
        <a href="{% url 'bugtracker:index'%}">Заявить</a>
      </li>
      <li class="{{page_in_progress}}">
        <a href="{% url 'bugtracker:in_progress_issues' %}">В работе</a>
      </li>
      <li class="{{page_solved}}">
        <a href="{% url 'bugtracker:solved_issues' %}">Решённые</a>
      </li>
      {% if user.is_authenticated %}
      <li class="{{page_profile}}">
        <a href="{% url 'bugtracker:profile' user.id %}">
          <span class="glyphicon glyphicon-user"></span>
            Профиль
        </a>
      </li>
      {% endif %}
    </ul>
    <ul class="nav navbar-nav navbar-right">
      {% if user.is_authenticated %}
      <li>
        <a href="{%url 'logout'%}?next={{request.path}}">
          <span class="glyphicon glyphicon-log-out"></span> Выход
        </a>
      </li>
      {% else %}
      <li>
        <a href="{%url 'bugtracker:register'%}">
          <span class="glyphicon glyphicon-user"></span> Регистрация
        </a>
      </li>
      <li>
        <a href="{%url 'login'%}?next={{request.path}}">
          <span class="glyphicon glyphicon-log-in"></span> Вход
        </a>
      </li>
      {% endif %}

    </ul>
  </div>
</nav> 

templates/bugtracker_app/profile.html
{% extends 'bugtracker_app/base.html'%}

{% block title %}
Профиль {{user.first_name}}
{% endblock%}

{% block content%}
<div class="container">
   <div class="row">
      <div class="col-md-4">
         {% include 'bugtracker_app/profile/profile_info.html' %}
      </div>
      <div class="col-md-8">
         {% include 'bugtracker_app/profile/profile_issues.html' %}
      </div>
   </div>
</div>
{% endblock %}

templates/bugtracker_app/solved_issues.html
{% extends 'bugtracker_app/issue_list.html'%}
{% block panel_class %}success{%endblock%}
{% block list_title %}Решённые заявки{% endblock %}

templates/bugtracker_app/thanks_for_report.html
{% extends 'bugtracker_app/base.html'%}
{% block title %}
Спасибо
{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="alert alert-success" role="alert">
        <h4 class="alert-heading">Спасибо! Номер вашей заявки
          <a href="{% url 'bugtracker:issue_detail' pk=report_issue_id %}">№{{report_issue_id}}</a>
         </h4>
        <p>Наши специалиcты уже работают над вашей заявкой.
         Мы пришлём вам уведомление, в случае обновления статуса заявки.</p>
        <hr>
        <a href="{% url 'bugtracker:index'%}" class="btn btn-success">Вернуться на главную</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/bugtracker_app/update_status.html
<form action="{%url 'bugtracker:update_status'%}" method="post">
	{% csrf_token %}
    <input type="submit" value="Update!" />  

</form>